version: "3.8"
services:
  sever_web:
    image: nginx
    ports:
      - "1200:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - estudo
  server_php_fpm:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - estudo
  db_postgres_sql:
    image: postgres:12
    container_name: pgsql_application
    restart: always
    tty: true
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=application_db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - estudo
volumes:
  postgres_data:
    driver: local

networks:
  estudo:
    name: network_estudo
    driver: bridge
